version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: haxis_django
    container_name: haxis_django
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.django
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    container_name: haxis_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=haxis_hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=catmeows

  redis:
    image: redis:7-alpine
    container_name: haxis_redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: haxis_celery_worker
    container_name: haxis_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.celery
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: haxis_celery_beat
    container_name: haxis_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.beat
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: haxis_celery_flower
    container_name: haxis_flower
    command: /start-flower.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.flower
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    
  mongo:
    image: mongo:latest
    container_name: haxis_mongo
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

volumes:
  postgres_data:
  mongo_data: